# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  pull_request: 
  workflow_dispatch:

      
    


jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: code checkout
      uses: actions/checkout@v7

    - name:
      run: |
         ls
         cat README.md

    - name:  terragrunt plan
      run: | 
         terragrunt init --terraform-non-interactive
         terragrunt plan --out=tfplan --terraform-non-interactive
    
    
    


   
