# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  #pull_request: 
  workflow_dispatch:


permissions:
    contents: read
    id-token: write

      
    


jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: code checkout
      uses: actions/checkout@v7


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
          role-to-assume: arn:aws:iam::730335466485:role/actions-terraform-ci
          aws-region: eu-west-1
          role-session-name: terraform-${{ github.run_id }}
          allowed-account-ids: "730335466485"

    - name: Verify AWS identity
      run: aws sts get-caller-identity



    - name: Setup Terraform
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: "1.14.6"
        terraform_wrapper: false
      
    - name: Gruntwork Terragrunt
      uses: gruntwork-io/terragrunt-action@8c1d96b76d445fd2e41475a3f0b63dcd1d9cc077
      with:
        tg_version: "1.1.2"
        tf_path: terraform

    - name: Terragrunt plan
      run: |
        terragrunt \
        --working-dir dev \
        --non-interactive \
        run --all \
        --out-dir "$GITHUB_WORKSPACE/tfplans/dev" \
        -- plan -input=false -no-color
