# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  pull_request: 
  workflow_dispatch:

      
    


jobs:
  terraform_workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: code checkout
      uses: actions/checkout@v7

    - name:
      run: |
         ls
         cat README.md
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      
    - name: Gruntwork Terragrunt
      uses: gruntwork-io/terragrunt-action@8c1d96b76d445fd2e41475a3f0b63dcd1d9cc077
      with:
        tg_version: "1.1.2"
        tf_path: terraform


  
  

    - name: Terragrunt plan
      run: |
        terragrunt --working-dir dev --non-interactive run -- init -input=false
        terragrunt --working-dir dev --non-interactive run -- plan -input=false -out=tfplan





        
    


   
